### ISSUE TITLE
Parameters list of a template

### ISSUE THREAD

**Issue by hhalex** [sunng87/handlebars-rust#622]
Hello,

thanks for the work, I am using Handlebars rs in a mock server project. The idea is to describe http routes and their associated responses in Yaml, with the ability to access some data from the request in the response description through handlebars templating system (this data would be accessible with some variables injected when rendering the template). 

```yaml
rules:
  - matches: POST /route/:path_param/end
    response: !Inline [200, "{ \"body_param\": \"{{body.json.my_param}}\", \"url_param\": \"{{url.path.path_param}}\"}"]
```

I want to provide a few options that would introduce a big overhead for each request/response if they were to computed for all requests, and that is why I want to compute only what is necessary according to what is used in the response.
So far, I’m checking what is used in response with regexes, but it could be cooler to have access to the parameters list of the template since Handlebars already does it?
