### ISSUE TITLE
Render a template with keeping indentation level of multi-line strings

### ISSUE THREAD

**Issue by inf17101** [sunng87/handlebars-rust#691]
I have the following issue with the default rendering:

```yaml
name: some name
data:
  key1: |
    {{value1}}
```

If I substitute it with a multi-line string using the default rendering syntax like above, then indentation level is lost and the resulting yaml is invalid:

substitution_string: `Line1\nLine2\nLine3`

```yaml
name: some name
data:
  key1: |
    Line1
Line2
Line3
```

What I need per default is:

```yaml
name: some name
data:
  key1: |
    Line1
    Line2
    Line3
```

I have tried out to register a partial because then the indentation level is kept and the rendering is fine. But then I need a custom syntax for my users like `{{> indent value1}}` (assume here the partial is registered with name 'indent').

Is there a programmatic way in the handlebars-rs library to enable to keep indentation level before rendering and disable it afterwars? I need it for one field and I need to change the default behavior.

What I have tried out: Register a template with `is_partial = true`, but the member and the `Template::compile2` to define TemplateOptions is also private.

Is there any way to keep indentation level with the default syntax without defining special helpers or custom syntax?
